apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpcloudapi-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcpcloudapi-backend
  template:
    metadata:
      labels:
        app: gcpcloudapi-backend
    spec:
      containers:
      - name: gcpcloudapi-backend
        image: gcr.io/gcpcloudproject-420220/gcpcloudapi:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "400Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gcpcloudapi-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: gcpcloudapi-backend
