apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpcloudapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcpcloudapi
  template:
    metadata:
      labels:
        app: gcpcloudapi
    spec:
      containers:
      - name: gcpcloudapi
        image: gcr.io/gcpcloudproject-420220/gcpcloudapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: "production"
        - name: DB_HOST
          value: "34.145.239.124"
        - name: DB_USER
          value: "dbadmin"
        - name: DB_PASS
          value: "Yellowstone2019"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gcpcloudapi-service
spec:
  selector:
    app: gcpcloudapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
