development:
  clients:
    default:
      database: gcp_cloud_api_development
      hosts:
        - 34.145.239.124:27017
      options:
        user: 'dbadmin'
        password: 'Yellowstone2019'
        auth_source: 'admin'
        # Enables client-side request validation by default.
        validate: true
        # Set the read preference if the application prefers reading from secondaries.
        read:
          mode: :nearest

test:
  clients:
    default:
      database: gcp_cloud_api_test
      hosts:
        - 34.145.239.124:27017
      options:
        read:
          mode: :primary
        # Reduce the max pool size for the test environment to minimize resources.
        max_pool_size: 5

production:
  clients:
   default:
      database: gcp_cloud_api_production
      hosts:
        - 34.145.239.124:27017
      options:
        user: 'dbadmin'
        password: 'Yellowstone2019'
        auth_source: 'admin'
        # Enables client-side request validation by default.
        validate: true
        read:
          mode: :nearest
        max_pool_size: 50
